version: '2'

services:
  db:
    environment:
      MYSQL_DATABASE: form
      MYSQL_PASSWORD: form
      MYSQL_ROOT_PASSWORD: form
      MYSQL_USER: form
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  nginx:
    image: nginx:1.11-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./web:/srv/form/web
  php:
    build: .
    depends_on:
      - db
    environment:
      SYMFONY_ENV: dev
    volumes:
      - ./:/srv/form
      - ./var/cache:/srv/form/var/cache
      - ./var/logs:/srv/form/var/logs
      - ./var/sessions:/srv/form/var/sessions
      - ./var:/srv/form/var
      - ./vendor:/srv/form/vendor
      - ./web:/srv/form/web

volumes:
  db-data: {}
