# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.form.extension:
         class: AppBundle\Extension\CountryExtension
         tags:
            - {name: twig.extension}

    app.controller.form:
          class: AppBundle\Controller\FormulaireController
          arguments:
              - "@doctrine"
              - "@knp_snappy.pdf"
              - "%kernel.root_dir%"
              - "@form.factory"
              - "@templating"
              - "@router"

